-- Migration 037: Skills and Licenses Lookup Tables
-- 250 searchable skills + 250 searchable licenses for helper profiles
-- OxSteed v2

CREATE TABLE IF NOT EXISTS skills_lookup (
  id       SERIAL PRIMARY KEY,
  name     VARCHAR(150) NOT NULL UNIQUE,
  category VARCHAR(100),
  is_active BOOLEAN DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_skills_lookup_search ON skills_lookup USING gin(to_tsvector('english', name));
CREATE INDEX IF NOT EXISTS idx_skills_lookup_category ON skills_lookup(category);

CREATE TABLE IF NOT EXISTS licenses_lookup (
  id       SERIAL PRIMARY KEY,
  name     VARCHAR(200) NOT NULL UNIQUE,
  category VARCHAR(100),
  is_active BOOLEAN DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_licenses_lookup_search ON licenses_lookup USING gin(to_tsvector('english', name));
CREATE INDEX IF NOT EXISTS idx_licenses_lookup_category ON licenses_lookup(category);

-- ─── 250 Skills ──────────────────────────────────────────────────────────────

INSERT INTO skills_lookup (name, category) VALUES
-- Home Repair & Handyman (20)
('Drywall Repair','Home Repair'),('Drywall Installation','Home Repair'),
('Door Installation','Home Repair'),('Window Installation','Home Repair'),
('Lock Installation','Home Repair'),('Ceiling Fan Installation','Home Repair'),
('Appliance Installation','Home Repair'),('Fixture Installation','Home Repair'),
('Shelf Installation','Home Repair'),('Furniture Assembly','Home Repair'),
('TV Mounting','Home Repair'),('Smoke Detector Installation','Home Repair'),
('Security Camera Installation','Home Repair'),('Attic Insulation','Home Repair'),
('Bathroom Remodel','Home Repair'),('Kitchen Remodel','Home Repair'),
('Deck Building','Home Repair'),('Fence Installation','Home Repair'),
('Tile Installation','Home Repair'),('Cabinet Installation','Home Repair'),
-- Landscaping & Outdoor (18)
('Lawn Mowing','Landscaping'),('Lawn Edging','Landscaping'),
('Lawn Aeration','Landscaping'),('Mulching','Landscaping'),
('Leaf Removal','Landscaping'),('Tree Trimming','Landscaping'),
('Tree Removal','Landscaping'),('Stump Grinding','Landscaping'),
('Shrub Trimming','Landscaping'),('Garden Bed Design','Landscaping'),
('Sod Installation','Landscaping'),('Irrigation System Installation','Landscaping'),
('Sprinkler Repair','Landscaping'),('Retaining Wall Installation','Landscaping'),
('Landscape Design','Landscaping'),('Landscape Lighting Installation','Landscaping'),
('Snow Plowing','Landscaping'),('Pressure Washing Driveway','Landscaping'),
-- Cleaning (15)
('Standard House Cleaning','Cleaning'),('Deep Cleaning','Cleaning'),
('Move-In Cleaning','Cleaning'),('Move-Out Cleaning','Cleaning'),
('Post-Construction Cleaning','Cleaning'),('Carpet Cleaning','Cleaning'),
('Window Cleaning','Cleaning'),('Oven Cleaning','Cleaning'),
('Pressure Washing','Cleaning'),('Air Duct Cleaning','Cleaning'),
('Dryer Vent Cleaning','Cleaning'),('Mold Remediation','Cleaning'),
('Vacation Rental Cleaning','Cleaning'),('Odor Removal','Cleaning'),
('Disinfection Services','Cleaning'),
-- Electrical (15)
('Panel Upgrade','Electrical'),('Circuit Breaker Replacement','Electrical'),
('GFCI Outlet Installation','Electrical'),('Outlet Installation','Electrical'),
('Dimmer Switch Installation','Electrical'),('Light Fixture Installation','Electrical'),
('Recessed Lighting Installation','Electrical'),('Ceiling Fan Wiring','Electrical'),
('EV Charger Installation','Electrical'),('Generator Installation','Electrical'),
('Smoke Detector Wiring','Electrical'),('Rewiring (Partial)','Electrical'),
('Rewiring (Full House)','Electrical'),('Electrical Troubleshooting','Electrical'),
('Outdoor Outlet Installation','Electrical'),
-- Plumbing (15)
('Faucet Installation','Plumbing'),('Faucet Repair','Plumbing'),
('Toilet Installation','Plumbing'),('Toilet Repair','Plumbing'),
('Water Heater Installation','Plumbing'),('Drain Cleaning','Plumbing'),
('Sewer Line Repair','Plumbing'),('Pipe Leak Repair','Plumbing'),
('Water Softener Installation','Plumbing'),('Garbage Disposal Installation','Plumbing'),
('Sump Pump Installation','Plumbing'),('Gas Line Installation','Plumbing'),
('Shower Installation','Plumbing'),('Repiping (Full House)','Plumbing'),
('Water Filter Installation','Plumbing'),
-- HVAC & Mechanical (14)
('AC Installation','HVAC'),('AC Repair','HVAC'),
('AC Tune-Up','HVAC'),('Furnace Installation','HVAC'),
('Furnace Repair','HVAC'),('Heat Pump Installation','HVAC'),
('Mini-Split Installation','HVAC'),('Thermostat Installation','HVAC'),
('Smart Thermostat Installation','HVAC'),('Ductwork Installation','HVAC'),
('Duct Cleaning','HVAC'),('HVAC Dryer Vent Cleaning','HVAC'),
('Air Filter Replacement','HVAC'),('Whole-Home Humidifier Installation','HVAC'),
-- Carpentry & Woodworking (17)
('Custom Cabinet Building','Carpentry'),('Built-In Shelving','Carpentry'),
('Crown Molding Installation','Carpentry'),('Baseboard Installation','Carpentry'),
('Wainscoting Installation','Carpentry'),('Barn Door Installation','Carpentry'),
('Stair Building','Carpentry'),('Custom Deck Construction','Carpentry'),
('Pergola Building','Carpentry'),('Fence Building','Carpentry'),
('Furniture Repair','Carpentry'),('Wood Rot Repair','Carpentry'),
('Load-Bearing Wall Framing','Carpentry'),('Window Seat Building','Carpentry'),
('Closet System Installation','Carpentry'),('Wood Flooring Installation','Carpentry'),
('Subfloor Installation','Carpentry'),
-- Painting & Finishing (14)
('Interior Wall Painting','Painting'),('Exterior House Painting','Painting'),
('Ceiling Painting','Painting'),('Trim Painting','Painting'),
('Cabinet Painting','Painting'),('Deck Staining','Painting'),
('Fence Staining','Painting'),('Epoxy Floor Coating','Painting'),
('Wallpaper Hanging','Painting'),('Wallpaper Removal','Painting'),
('Popcorn Ceiling Removal','Painting'),('Spray Painting Exterior','Painting'),
('Surface Preparation','Painting'),('Paint Stripping','Painting'),
-- Roofing & Gutters (10)
('Roof Inspection','Roofing'),('Shingle Replacement Partial','Roofing'),
('Shingle Replacement Full','Roofing'),('Metal Roof Installation','Roofing'),
('Flat Roof Repair','Roofing'),('Chimney Flashing Repair','Roofing'),
('Ice Dam Removal','Roofing'),('Gutter Installation','Roofing'),
('Gutter Cleaning','Roofing'),('Gutter Guard Installation','Roofing'),
-- Flooring (13)
('Hardwood Floor Installation','Flooring'),('Hardwood Floor Refinishing','Flooring'),
('Laminate Flooring Installation','Flooring'),('Vinyl Plank Installation','Flooring'),
('Tile Flooring Installation','Flooring'),('Carpet Installation','Flooring'),
('Carpet Stretching','Flooring'),('Epoxy Floor Installation','Flooring'),
('Subfloor Leveling','Flooring'),('Grout Sealing','Flooring'),
('Radiant Heat Flooring Installation','Flooring'),('Hardwood Floor Sanding','Flooring'),
('Luxury Vinyl Tile Installation','Flooring'),
-- Moving & Hauling (10)
('Local Moving','Moving'),('Long Distance Moving','Moving'),
('Loading and Unloading','Moving'),('Furniture Disassembly and Reassembly','Moving'),
('Piano Moving','Moving'),('Junk Removal','Moving'),
('Packing Services','Moving'),('Appliance Removal','Moving'),
('Estate Cleanout','Moving'),('Storage Unit Moving','Moving'),
-- Auto & Vehicle (13)
('Oil Change','Auto'),('Tire Rotation','Auto'),
('Brake Pad Replacement','Auto'),('Battery Replacement','Auto'),
('Full Car Detailing','Auto'),('Interior Detailing','Auto'),
('Windshield Chip Repair','Auto'),('Paintless Dent Removal','Auto'),
('OBD Diagnostic Scan','Auto'),('Mobile Mechanic Service','Auto'),
('Pre-Purchase Vehicle Inspection','Auto'),('Tire Installation','Auto'),
('Ceramic Coating Application','Auto'),
-- Pest Control (8)
('General Pest Inspection','Pest Control'),('Termite Treatment','Pest Control'),
('Bed Bug Treatment','Pest Control'),('Rodent Extermination','Pest Control'),
('Mosquito Control','Pest Control'),('Wasp Nest Removal','Pest Control'),
('Wildlife Removal','Pest Control'),('Fumigation Services','Pest Control'),
-- Tech Support & Smart Home (15)
('Computer Setup and Configuration','Tech Support'),('Virus and Malware Removal','Tech Support'),
('Data Recovery','Tech Support'),('WiFi Router Setup','Tech Support'),
('Smart TV Setup','Tech Support'),('Smart Thermostat Setup and Programming','Tech Support'),
('Smart Doorbell Installation','Tech Support'),('Smart Lock Setup','Tech Support'),
('Home Security Camera Setup','Tech Support'),('Home Theater Setup','Tech Support'),
('TV Wall Mount Installation','Tech Support'),('Network Setup','Tech Support'),
('Smart Home Consultation','Tech Support'),('Laptop Repair','Tech Support'),
('Smart Speaker Setup','Tech Support'),
-- Personal Services & Wellness (20)
('Personal Training','Personal Services'),('Yoga Instruction','Personal Services'),
('Nutrition Consultation','Personal Services'),('Meal Prep Services','Personal Services'),
('Grocery Shopping','Personal Services'),('Errand Running','Personal Services'),
('House Sitting','Personal Services'),('Home Organization','Personal Services'),
('Senior Care Assistance','Personal Services'),('Elementary Tutoring','Personal Services'),
('High School Tutoring','Personal Services'),('Guitar Lessons','Personal Services'),
('Piano Lessons','Personal Services'),('Language Lessons','Personal Services'),
('Life Coaching','Personal Services'),('Resume Writing','Personal Services'),
('Notary Services','Personal Services'),('Personal Chef Services','Personal Services'),
('Personal Tax Preparation','Personal Services'),('Bookkeeping','Personal Services'),
-- Pet Care (10)
('Dog Walking','Pet Care'),('Cat Sitting','Pet Care'),
('Dog Sitting','Pet Care'),('Pet Grooming','Pet Care'),
('Dog Nail Trimming','Pet Care'),('Dog Training Basic Obedience','Pet Care'),
('Pet Transportation','Pet Care'),('Aquarium Maintenance','Pet Care'),
('Pet Waste Removal','Pet Care'),('Overnight Pet Sitting','Pet Care'),
-- Photography & Media (12)
('Portrait Photography','Photography'),('Wedding Photography','Photography'),
('Real Estate Photography','Photography'),('Product Photography','Photography'),
('Video Production','Photography'),('Drone Aerial Photography','Photography'),
('Photo Editing','Photography'),('Video Editing','Photography'),
('Social Media Content Creation','Photography'),('Headshot Photography','Photography'),
('Event Photography','Photography'),('Photo Restoration','Photography'),
-- Event Planning & Entertainment (11)
('Wedding Coordination','Events'),('Event Decor Setup','Events'),
('DJ Services','Events'),('Party Planning','Events'),
('Corporate Event Planning','Events'),('Catering Assistance','Events'),
('Bartending','Events'),('Face Painting','Events'),
('Event Setup Labor','Events'),('Event Cleanup','Events'),
('Kids Party Planning','Events')
ON CONFLICT (name) DO NOTHING;

-- ─── 250 Licenses ────────────────────────────────────────────────────────────

INSERT INTO licenses_lookup (name, category) VALUES
-- Electrical (20)
('Master Electrician License','Electrical'),('Journeyman Electrician License','Electrical'),
('Residential Electrician License','Electrical'),('Commercial Electrician License','Electrical'),
('Low-Voltage Technician License','Electrical'),('Electrical Contractor License','Electrical'),
('Solar PV Installer Certification (NABCEP)','Electrical'),
('EV Infrastructure Training Program (EVITP)','Electrical'),
('OSHA 10 Electrical','Electrical'),('NFPA 70E Electrical Safety Certification','Electrical'),
('Electrician Apprentice License','Electrical'),('Fire Alarm Electrician License','Electrical'),
('Sign Electrician License','Electrical'),('Communications Electrician License','Electrical'),
('Generator Technician Certification','Electrical'),
('Battery Storage Installer Certification','Electrical'),
('Licensed Electrical Inspector','Electrical'),('Low-Voltage Contractor License','Electrical'),
('Industrial Electrician License','Electrical'),
('Hazardous Location Wiring Certification','Electrical'),
-- Plumbing (20)
('Master Plumber License','Plumbing'),('Journeyman Plumber License','Plumbing'),
('Plumbing Contractor License','Plumbing'),('Residential Plumber License','Plumbing'),
('Commercial Plumber License','Plumbing'),
('Backflow Prevention Assembly Tester Certification','Plumbing'),
('Gas Piping License','Plumbing'),('Medical Gas Installer (ASSE 6010)','Plumbing'),
('Fire Sprinkler Contractor License','Plumbing'),('Irrigation Contractor License','Plumbing'),
('Certified Irrigation Technician (CIT)','Plumbing'),('Well Driller License','Plumbing'),
('Septic System Installer License','Plumbing'),('Plumbing Inspector License','Plumbing'),
('Drain Cleaner License','Plumbing'),('Water Treatment Specialist Certification','Plumbing'),
('Plumber Apprentice License','Plumbing'),('Sewer Pipe Layer License','Plumbing'),
('Water Distribution Operator License','Plumbing'),
('Wastewater Treatment Operator License','Plumbing'),
-- HVAC (15)
('EPA 608 Universal Certification','HVAC'),('NATE Core Certification','HVAC'),
('NATE Air Conditioning Service Certification','HVAC'),
('NATE Heat Pump Service Certification','HVAC'),
('NATE Gas Furnace Service Certification','HVAC'),
('HVAC Excellence Master Technician','HVAC'),('BPI Building Analyst Professional','HVAC'),
('Mechanical Contractor License','HVAC'),('HVAC Contractor License','HVAC'),
('Refrigeration Technician License','HVAC'),('Boiler Operator License','HVAC'),
('Stationary Engineer License','HVAC'),('Certified Energy Auditor (CEA)','HVAC'),
('IGSHPA Accredited Installer','HVAC'),('OSHA 10 HVAC','HVAC'),
-- Contractor & Construction (20)
('General Contractor License','Contractor'),('Residential Builder License','Contractor'),
('Home Improvement Contractor License','Contractor'),
('Roofing Contractor License','Contractor'),('Flooring Contractor License','Contractor'),
('Masonry Contractor License','Contractor'),('Concrete Contractor License','Contractor'),
('Drywall Contractor License','Contractor'),('Swimming Pool Contractor License','Contractor'),
('Demolition Contractor License','Contractor'),
('Asbestos Removal Contractor License','Contractor'),
('Lead Paint Abatement Contractor License','Contractor'),
('OSHA 10 Construction','Contractor'),('OSHA 30 Construction','Contractor'),
('ICC Residential Building Inspector Certification','Contractor'),
('LEED AP BD+C Certification','Contractor'),('Scaffold Contractor License','Contractor'),
('Waterproofing Contractor License','Contractor'),
('Insulation Contractor License','Contractor'),
('Window and Door Contractor License','Contractor'),
-- Auto & Vehicle (13)
('ASE Master Technician Certification','Auto'),('ASE Engine Repair A1','Auto'),
('ASE Brakes A5','Auto'),('ASE Electrical Systems A6','Auto'),
('ASE Heating and Air Conditioning A7','Auto'),('ASE Engine Performance A8','Auto'),
('ASE Collision Repair Certification','Auto'),('ICAR Gold Class Certification','Auto'),
('State Vehicle Safety Inspection License','Auto'),('Motor Vehicle Dealer License','Auto'),
('Automotive Glass Technician (AGRSS)','Auto'),
('Electric Vehicle Technician Certification','Auto'),
('Forklift Operator Safety Certification','Auto'),
-- Healthcare & Wellness (28)
('CPR/AED Certification (AHA)','Healthcare'),('First Aid Certification','Healthcare'),
('BLS Provider (AHA)','Healthcare'),('Emergency Medical Technician (EMT-B)','Healthcare'),
('Registered Nurse (RN)','Healthcare'),('Licensed Practical Nurse (LPN)','Healthcare'),
('Certified Nursing Assistant (CNA)','Healthcare'),('Home Health Aide (HHA)','Healthcare'),
('Certified Medical Assistant (CMA)','Healthcare'),
('Phlebotomy Technician Certification','Healthcare'),
('Physical Therapist License (PT)','Healthcare'),
('Occupational Therapist License (OTR/L)','Healthcare'),
('Speech Language Pathologist License','Healthcare'),('Registered Dietitian (RD)','Healthcare'),
('Certified Personal Trainer (NASM)','Healthcare'),('Certified Personal Trainer (ACE)','Healthcare'),
('200-Hour RYT Yoga Instructor','Healthcare'),('Licensed Massage Therapist (LMT)','Healthcare'),
('Acupuncture License (L.Ac.)','Healthcare'),('Chiropractic Doctor License (DC)','Healthcare'),
('Board Certified Behavior Analyst (BCBA)','Healthcare'),
('Mental Health First Aid Certification','Healthcare'),
('Substance Abuse Counselor Certification','Healthcare'),
('Certified Case Manager (CCM)','Healthcare'),
('International Board Certified Lactation Consultant (IBCLC)','Healthcare'),
('DONA Doula Certification','Healthcare'),
('Certified Therapeutic Recreation Specialist (CTRS)','Healthcare'),
('Bloodborne Pathogen Certification','Healthcare'),
-- Food & Hospitality (13)
('ServSafe Food Handler Certification','Food & Hospitality'),
('ServSafe Food Protection Manager Certification','Food & Hospitality'),
('ServSafe Alcohol Certification','Food & Hospitality'),
('ANSI Food Manager Certification','Food & Hospitality'),
('Responsible Beverage Service Certificate','Food & Hospitality'),
('Bartender License','Food & Hospitality'),
('SCA Barista Certification','Food & Hospitality'),
('WSET Level 2 Award in Wine','Food & Hospitality'),
('Certified Culinary Professional (CCP)','Food & Hospitality'),
('HACCP Certification','Food & Hospitality'),('Food Truck Business License','Food & Hospitality'),
('Cottage Food Producer License','Food & Hospitality'),
('Allergen Awareness Certificate','Food & Hospitality'),
-- Real Estate & Property (13)
('Real Estate Salesperson License','Real Estate'),('Real Estate Broker License','Real Estate'),
('Certified Residential Specialist (CRS)','Real Estate'),
('Certified Property Manager (CPM)','Real Estate'),
('Home Inspector License','Real Estate'),('Certified Home Inspector (NAHI)','Real Estate'),
('HUD Certified Housing Counselor','Real Estate'),
('Certified Residential Appraiser','Real Estate'),('Home Stager Certification','Real Estate'),
('Mortgage Loan Originator License (MLO)','Real Estate'),
('Lead Paint Inspector License','Real Estate'),('Radon Measurement Technician','Real Estate'),
('HERS Energy Rater Certification','Real Estate'),
-- Financial & Legal (13)
('Certified Public Accountant (CPA)','Financial & Legal'),
('IRS Enrolled Agent (EA)','Financial & Legal'),
('Certified Financial Planner (CFP)','Financial & Legal'),
('FINRA Series 7 License','Financial & Legal'),
('FINRA Series 65 License','Financial & Legal'),
('Certified Bookkeeper (CB)','Financial & Legal'),
('QuickBooks ProAdvisor Certification','Financial & Legal'),
('Certified Payroll Professional (CPP)','Financial & Legal'),
('Notary Public Commission','Financial & Legal'),
('NALA Certified Paralegal','Financial & Legal'),
('Certified Mediator','Financial & Legal'),
('Certified Fraud Examiner (CFE)','Financial & Legal'),
('FINRA Series 63 License','Financial & Legal'),
-- Education & Childcare (15)
('Child Development Associate (CDA)','Education'),
('Montessori Primary Certification','Education'),('Elementary Teaching License','Education'),
('Special Education Teaching License','Education'),
('ESL/ELL Teaching Certification','Education'),('TESOL Certificate','Education'),
('Reading Specialist Certification','Education'),
('NTPS Tutoring Certification','Education'),('After School Program Director License','Education'),
('Child Life Specialist Certification','Education'),
('Childcare Center Director License','Education'),
('Family Childcare Provider License','Education'),('Nanny Certification (NCS)','Education'),
('Mandated Reporter Training Certificate','Education'),
('Pediatric First Aid Certification','Education'),
-- Security (10)
('Unarmed Security Guard License','Security'),('Armed Security Guard License','Security'),
('Private Investigator License','Security'),('Alarm System Installer License','Security'),
('Certified Protection Professional (CPP)','Security'),
('Loss Prevention Agent Certification','Security'),
('Event Security Specialist Certification','Security'),('CompTIA Security+ Certification','Security'),
('CISSP Certification','Security'),('Certified Ethical Hacker (CEH)','Security'),
-- Transportation (13)
('Commercial Driver''s License (CDL-A)','Transportation'),
('CDL Class B License','Transportation'),
('CDL Hazardous Materials Endorsement','Transportation'),
('FMCSA Medical Examiner Certificate','Transportation'),
('OSHA Forklift Safety Certification','Transportation'),
('NCCCO Crane Operator License','Transportation'),
('Taxi and Rideshare Driver License','Transportation'),
('School Bus Driver License','Transportation'),
('Non-Emergency Medical Transport License','Transportation'),
('TWIC Card (Maritime Security)','Transportation'),
('USCG Marine Captain License','Transportation'),
('FAA Part 107 Commercial Drone Pilot','Transportation'),
('CDL Passenger Endorsement','Transportation'),
-- Environmental & Pest Control (13)
('Structural Pesticide Applicator License','Environmental'),
('Lawn and Ornamental Pesticide License','Environmental'),
('Certified Pest Control Operator','Environmental'),
('Fumigator License','Environmental'),('Termite Inspector Certification','Environmental'),
('Wildlife Control Operator License','Environmental'),
('Integrated Pest Management (IPM) Specialist','Environmental'),
('HAZWOPER 40-Hour Certification','Environmental'),
('Lead Abatement Worker License','Environmental'),
('Asbestos Inspector License','Environmental'),
('Mold Remediation Contractor License','Environmental'),
('Radon Mitigation Specialist Certification','Environmental'),
('Certified Indoor Environmentalist (CIE)','Environmental'),
-- Beauty & Personal Care (20)
('Cosmetology License','Beauty'),('Esthetician License','Beauty'),
('Barber License','Beauty'),('Nail Technician License','Beauty'),
('Makeup Artist Certification','Beauty'),('Permanent Makeup Artist License','Beauty'),
('Microblading Certification','Beauty'),('Lash Extension Certification','Beauty'),
('Laser Hair Removal Technician License','Beauty'),('Electrology License','Beauty'),
('Medical Laser Technician License','Beauty'),
('Medical Aesthetics Certification','Beauty'),('Chemical Peel Certification','Beauty'),
('Spray Tanning Certification','Beauty'),
('Advanced Hair Coloring Certificate','Beauty'),
('Natural Hair Specialist Certification','Beauty'),
('Cosmetology Instructor License','Beauty'),('Esthetics Instructor License','Beauty'),
('Barber Instructor License','Beauty'),('Salon Manager Certification','Beauty'),
-- Technology (15)
('CompTIA A+ Certification','Technology'),('CompTIA Network+ Certification','Technology'),
('CompTIA Security+ Certification (IT)','Technology'),
('Microsoft Azure Fundamentals (AZ-900)','Technology'),
('Microsoft Azure Administrator (AZ-104)','Technology'),
('Google Cloud Associate Cloud Engineer','Technology'),
('AWS Cloud Practitioner Certification','Technology'),
('AWS Certified Solutions Architect','Technology'),('Cisco CCNA Certification','Technology'),
('Apple Certified Support Professional (ACSP)','Technology'),
('ITIL Foundation Certificate','Technology'),
('PMP Project Management Professional','Technology'),
('Certified Scrum Master (CSM)','Technology'),
('Six Sigma Green Belt Certification','Technology'),
('Google Analytics Individual Qualification','Technology'),
-- Other Professional (9)
('Certified Interior Designer (CID)','Other Professional'),
('Certified Kitchen Designer (CKD)','Other Professional'),
('CAPS Certified Aging-in-Place Specialist','Other Professional'),
('ISA Certified Arborist','Other Professional'),
('Registered Landscape Architect','Other Professional'),
('NFPA Fire Inspector Level I','Other Professional'),
('Certified Safety Professional (CSP)','Other Professional'),
('Certified Industrial Hygienist (CIH)','Other Professional'),
('Professional Land Surveyor (PLS)','Other Professional')
ON CONFLICT (name) DO NOTHING;
