-- Migration 053: Expand Skills and Licenses to 1,000 entries each
-- Skills: adds 750 new entries derived from services.md (250 already seeded in 037)
-- Licenses: adds 500 new entries across all 21 service domains (250 already seeded in 037)
-- All inserts use ON CONFLICT (name) DO NOTHING — fully idempotent and safe to replay
-- OxSteed v2

-- ─── 750 New Skills ────────────────────────────────────────────────────────

INSERT INTO skills_lookup (name, category) VALUES
('4-tire replacement (mid-range vehicle)','Auto'),
('4WD/AWD system service','Auto'),
('A/C compressor replacement','Auto'),
('A/C condenser replacement','Auto'),
('A/C evaporator replacement','Auto'),
('A/C recharge (refrigerant)','Auto'),
('Air filter replacement (engine)','Auto'),
('Alternator replacement','Auto'),
('Anti-roll bar replacement','Auto'),
('Auto detailing (exterior)','Auto'),
('Auto detailing (full detail)','Auto'),
('Auto detailing (interior)','Auto'),
('Axle seal replacement','Auto'),
('Backup camera installation','Auto'),
('Ball joint replacement','Auto'),
('Battery replacement','Auto'),
('Blower motor replacement','Auto'),
('Brake caliper replacement','Auto'),
('Brake fluid flush','Auto'),
('Brake rotor replacement (per axle)','Auto'),
('Bumper repair/repaint','Auto'),
('CV axle replacement','Auto'),
('CV joint boot replacement','Auto'),
('Cabin air filter replacement','Auto'),
('Car stereo/radio installation','Auto'),
('Catalytic converter replacement','Auto'),
('Ceramic coating (full car)','Auto'),
('Chrome delete/vinyl wrap (partial)','Auto'),
('Clutch replacement','Auto'),
('Control arm replacement','Auto'),
('Coolant flush','Auto'),
('Dent removal (PDR, per dent)','Auto'),
('Differential fluid change','Auto'),
('Door handle replacement (exterior)','Auto'),
('Door lock actuator replacement','Auto'),
('EV battery replacement','Auto'),
('Engine oil pan gasket replacement','Auto'),
('Engine replacement (long block)','Auto'),
('Engine replacement (short block)','Auto'),
('Exhaust pipe repair','Auto'),
('Front brake pad replacement','Auto'),
('Fuel filter replacement','Auto'),
('Fuel injector cleaning','Auto'),
('Fuel injector replacement (per injector)','Auto'),
('Fuel pump replacement','Auto'),
('Head gasket replacement','Auto'),
('Headlight assembly replacement','Auto'),
('Headlight bulb replacement (per bulb)','Auto'),
('Heater core replacement','Auto'),
('Hybrid battery replacement','Auto'),
('Ignition switch replacement','Auto'),
('Key fob programming','Auto'),
('Lift kit installation (truck/SUV)','Auto'),
('Mass air flow sensor replacement','Auto'),
('Muffler replacement','Auto'),
('New tire installation (per tire)','Auto'),
('OBD-II diagnostic scan','Auto'),
('Odometer/speedometer calibration','Auto'),
('Oil change (conventional)','Auto'),
('Oil change (synthetic)','Auto'),
('Oxygen sensor replacement','Auto'),
('Paint protection film (per panel)','Auto'),
('Paint scratch repair (minor)','Auto'),
('Power steering fluid flush','Auto'),
('Power steering pump replacement','Auto'),
('Power steering rack replacement','Auto'),
('Power window motor replacement','Auto'),
('Pre-purchase inspection','Auto'),
('Radiator replacement','Auto'),
('Rear brake pad replacement','Auto'),
('Remote start installation','Auto'),
('Running board installation','Auto'),
('Serpentine belt replacement','Auto'),
('Side mirror replacement','Auto'),
('Spark plug replacement (4-cyl)','Auto'),
('Spark plug replacement (V6/V8)','Auto'),
('Starter motor replacement','Auto'),
('State safety/emissions inspection','Auto'),
('Strut replacement (pair)','Auto'),
('Strut/shock absorber replacement (per corner)','Auto'),
('Suspension spring replacement','Auto'),
('Sway bar link replacement','Auto'),
('TPMS sensor replacement (per sensor)','Auto'),
('Tail light assembly replacement','Auto'),
('Thermostat replacement','Auto'),
('Throttle body cleaning','Auto'),
('Tie rod end replacement','Auto'),
('Timing belt replacement','Auto'),
('Timing chain replacement','Auto'),
('Tire balance','Auto'),
('Tire patch/plug repair','Auto'),
('Tire rotation','Auto'),
('Tire rotation + balance combo','Auto'),
('Transfer case fluid change','Auto'),
('Transmission fluid change (automatic)','Auto'),
('Transmission fluid change (manual)','Auto'),
('Transmission rebuild','Auto'),
('Transmission replacement','Auto'),
('Turn signal bulb replacement','Auto'),
('Valve cover gasket replacement','Auto'),
('Water pump replacement','Auto'),
('Wheel alignment (2-wheel)','Auto'),
('Wheel alignment (4-wheel)','Auto'),
('Wheel bearing replacement','Auto'),
('Window regulator replacement','Auto'),
('Window tinting (full car)','Auto'),
('Windshield chip repair','Auto'),
('Windshield replacement','Auto'),
('Wiper blade replacement (pair)','Auto'),
('Wiper motor replacement','Auto'),
('Acrylic full set','Beauty'),
('Basic manicure','Beauty'),
('Basic pedicure','Beauty'),
('Beard trim/styling','Beauty'),
('Bikini wax (standard)','Beauty'),
('Blowout / blow-dry styling','Beauty'),
('Body piercing (cartilage/nose)','Beauty'),
('Botox injection (per unit)','Beauty'),
('Chemical peel (light)','Beauty'),
('Children''s haircut','Beauty'),
('Coolsculpting (per area)','Beauty'),
('Couples massage (60 min)','Beauty'),
('Deep cleansing facial','Beauty'),
('Dermal filler (per syringe)','Beauty'),
('Dermaplaning facial','Beauty'),
('Ear piercing (per ear)','Beauty'),
('Eyebrow waxing/threading','Beauty'),
('Eyelash extensions (full set)','Beauty'),
('Facial (standard)','Beauty'),
('Full body wax','Beauty'),
('Full hair color','Beauty'),
('Full highlight/balayage','Beauty'),
('Full leg wax','Beauty'),
('Full makeup application','Beauty'),
('Gel manicure','Beauty'),
('Gel pedicure','Beauty'),
('Hair relaxer','Beauty'),
('Hair toning/gloss','Beauty'),
('Hot stone massage (60 min)','Beauty'),
('HydraFacial','Beauty'),
('Keratin treatment / Brazilian blowout','Beauty'),
('Kybella (double chin, per session)','Beauty'),
('LED light therapy (face)','Beauty'),
('Laser hair removal (per session, large area)','Beauty'),
('Laser hair removal (per session, small area)','Beauty'),
('Lash fill','Beauty'),
('Lice removal service (in-home)','Beauty'),
('Lice removal treatment (clinic)','Beauty'),
('Lip wax','Beauty'),
('Massage (Swedish, 60 min)','Beauty'),
('Massage (deep tissue, 60 min)','Beauty'),
('Men''s haircut (standard)','Beauty'),
('Microblading (eyebrows)','Beauty'),
('Microdermabrasion','Beauty'),
('Nail fill (acrylic)','Beauty'),
('Oxygen facial','Beauty'),
('Partial highlight/balayage','Beauty'),
('Perm','Beauty'),
('Permanent makeup (lip color)','Beauty'),
('Plasma pen treatment (per area)','Beauty'),
('Scalp treatment (dandruff/psoriasis)','Beauty'),
('Spray tan','Beauty'),
('Tattoo (large, sleeve/back)','Beauty'),
('Tattoo (medium, palm-sized)','Beauty'),
('Tattoo (small, under 2 in)','Beauty'),
('Tattoo removal (per session)','Beauty'),
('Teeth whitening (in-office)','Beauty'),
('Updo / special occasion styling','Beauty'),
('Vampire facial (PRP)','Beauty'),
('Wigs/extensions application','Beauty'),
('Women''s haircut (standard)','Beauty'),
('Air duct cleaning (avg home)','Cleaning'),
('Basement cleaning/organization','Cleaning'),
('Biohazard/trauma cleaning','Cleaning'),
('Carpet cleaning (3 rooms)','Cleaning'),
('Chimney sweeping','Cleaning'),
('Commercial cleaning (per sq ft/month)','Cleaning'),
('Crawlspace cleaning','Cleaning'),
('Deep cleaning (full home)','Cleaning'),
('Dry cleaning (per garment)','Cleaning'),
('Dryer vent cleaning (cleaning)','Cleaning'),
('Dumpster rental (7-day, 10 yd)','Cleaning'),
('Fire/smoke damage cleanup','Cleaning'),
('Flood/water damage cleanup','Cleaning'),
('Garage cleaning (full)','Cleaning'),
('Gutter cleaning','Cleaning'),
('Hardwood floor buffing/polishing','Cleaning'),
('Hoarding cleanup (per room)','Cleaning'),
('House cleaning (standard, 1,000 sq ft)','Cleaning'),
('House cleaning (standard, 2,000 sq ft)','Cleaning'),
('Junk removal (full truckload)','Cleaning'),
('Junk removal (small load)','Cleaning'),
('Laundry service (drop-off, per lb)','Cleaning'),
('Mattress cleaning (per mattress)','Cleaning'),
('Mold remediation (large area)','Cleaning'),
('Mold remediation (small area)','Cleaning'),
('Move-in/move-out cleaning','Cleaning'),
('Office cleaning (small office/week)','Cleaning'),
('Oven cleaning (deep clean)','Cleaning'),
('Pool cleaning (weekly service)','Cleaning'),
('Pool closing (seasonal)','Cleaning'),
('Pool opening (seasonal)','Cleaning'),
('Post-construction cleaning','Cleaning'),
('Power washing (deck)','Cleaning'),
('Pressure washing (driveway)','Cleaning'),
('Pressure washing (house exterior)','Cleaning'),
('Refrigerator cleaning (deep)','Cleaning'),
('Tile and grout cleaning (per sq ft)','Cleaning'),
('Tile grout recoloring (per sq ft)','Cleaning'),
('Upholstery cleaning (per piece)','Cleaning'),
('Window cleaning (interior/exterior)','Cleaning'),
('ADHD/learning disability tutoring','Education'),
('Academic coaching (per hour)','Education'),
('Art lessons (per hour)','Education'),
('Behind-the-wheel driving lesson','Education'),
('CPR certification class','Education'),
('Career coaching (per session)','Education'),
('Coding bootcamp (full program)','Education'),
('College admissions consulting','Education'),
('College essay review/editing','Education'),
('Continuing education course (per credit)','Education'),
('Corporate training (half-day workshop)','Education'),
('Culinary arts class (per session)','Education'),
('Dance lessons (group class)','Education'),
('Dance lessons (private, per hour)','Education'),
('Driving school (full program)','Education'),
('Drum lessons (per hour)','Education'),
('English as second language class (per hour)','Education'),
('Executive coaching (per session)','Education'),
('Financial aid counseling (FAFSA)','Education'),
('First aid certification','Education'),
('Foreign language tutoring (per hour)','Education'),
('Forklift certification class','Education'),
('GMAT/GRE test prep tutoring','Education'),
('Graduate school application consulting','Education'),
('Homeschool curriculum consultation','Education'),
('IEP coaching','Education'),
('Interview coaching (per session)','Education'),
('LSAT prep course (full)','Education'),
('Life coaching (per session)','Education'),
('LinkedIn profile optimization','Education'),
('MCAT prep course (full)','Education'),
('Motorcycle safety course (MSF)','Education'),
('Music lessons (piano/guitar, per hour)','Education'),
('OSHA 10-hour safety course','Education'),
('Online course creation consultation','Education'),
('Online course subscription (per month)','Education'),
('Photography course (full)','Education'),
('Private tutoring (K-8 general)','Education'),
('Private tutoring (high school)','Education'),
('Professional certification prep (per hour)','Education'),
('Real estate exam prep course','Education'),
('Resume writing service','Education'),
('SAT/ACT prep course (full)','Education'),
('SAT/ACT test prep tutoring','Education'),
('Scholarship search service','Education'),
('Special needs tutoring (per hour)','Education'),
('Sports coaching (youth, per session)','Education'),
('Standardized test accommodations planning','Education'),
('Swim lessons (group)','Education'),
('Swim lessons (private)','Education'),
('Voice lessons (per hour)','Education'),
('220V outlet installation (dryer/range)','Electrical'),
('Attic ventilation fan install','Electrical'),
('Backup battery system install','Electrical'),
('Bathroom exhaust fan install','Electrical'),
('Carbon monoxide detector install','Electrical'),
('Ceiling fan installation (existing wiring)','Electrical'),
('Ceiling fan installation (new wiring)','Electrical'),
('Circuit breaker replacement','Electrical'),
('Dedicated circuit for appliance','Electrical'),
('Dimmer switch installation','Electrical'),
('Doorbell installation (wired)','Electrical'),
('EV charger installation (Level 2)','Electrical'),
('Electrical inspection','Electrical'),
('Electrical troubleshooting (per hour)','Electrical'),
('GFCI outlet installation','Electrical'),
('Generator hookup (transfer switch)','Electrical'),
('Ground fault circuit installation','Electrical'),
('Home theater wiring','Electrical'),
('Hot tub electrical hookup','Electrical'),
('Landscape low-voltage lighting install','Electrical'),
('Light fixture installation (standard)','Electrical'),
('Light switch replacement','Electrical'),
('New circuit addition','Electrical'),
('New electrical panel installation','Electrical'),
('Outdoor electrical outlet installation','Electrical'),
('Outdoor light installation','Electrical'),
('Outlet repair/replacement','Electrical'),
('Panel upgrade (100A to 200A)','Electrical'),
('Pool/spa electrical hookup','Electrical'),
('Recessed lighting installation (per light)','Electrical'),
('Security system wiring','Electrical'),
('Smart thermostat installation','Electrical'),
('Smoke detector installation','Electrical'),
('Solar panel system installation (avg home)','Electrical'),
('Standby generator installation','Electrical'),
('USB outlet installation','Electrical'),
('Video doorbell installation','Electrical'),
('Whole-house fan installation','Electrical'),
('Whole-house rewiring (per room)','Electrical'),
('Whole-house surge protector install','Electrical'),
('Balloon artist (per hour)','Events'),
('Bartending service (4 hours)','Events'),
('Birthday cake custom order (per serving)','Events'),
('Bounce house rental (half day)','Events'),
('Catering (buffet, per person)','Events'),
('Chair/table rental (per item)','Events'),
('Children''s birthday party entertainer','Events'),
('Clown/magician (per hour)','Events'),
('Conference AV setup (full day)','Events'),
('Cooking class event (per person)','Events'),
('Corporate event planning','Events'),
('Corporate headshot day (per person)','Events'),
('Corporate lunch catering (per person)','Events'),
('Dessert table setup (events)','Events'),
('Escape room rental (private)','Events'),
('Event MC/host (4 hours)','Events'),
('Event cleanup service','Events'),
('Event lighting rental/setup','Events'),
('Event sound system setup','Events'),
('Event staffing (server per hour)','Events'),
('Event venue rental (small, per day)','Events'),
('Face painting (per hour)','Events'),
('Floral arrangement (centerpiece)','Events'),
('Food truck rental (per event)','Events'),
('Graduation party catering (per person)','Events'),
('Holiday party planning','Events'),
('Murder mystery event (per guest)','Events'),
('Party tent rental','Events'),
('Photo booth + digital downloads','Events'),
('Photo booth rental (event)','Events'),
('Private chef (dinner party, 8 guests)','Events'),
('Team building workshop facilitation','Events'),
('Valet parking service (per event)','Events'),
('Wedding DJ (4-6 hours)','Events'),
('Wedding band (4 musicians, 4 hours)','Events'),
('Wedding cake (per serving)','Events'),
('Wedding catering (per person)','Events'),
('Wedding florist (full ceremony+reception)','Events'),
('Wedding photography (full day)','Events'),
('Wedding planner (full service)','Events'),
('Wedding videography','Events'),
('Wine tasting event coordination','Events'),
('1031 exchange facilitation','Financial'),
('1099 contractor tax filing','Financial'),
('529 college savings plan setup','Financial'),
('Annuity analysis','Financial'),
('Bookkeeping (monthly, small business)','Financial'),
('Business audit (CPA)','Financial'),
('Business plan writing','Financial'),
('Business tax return (S-Corp/LLC)','Financial'),
('Business valuation (small business)','Financial'),
('Cash flow projection model','Financial'),
('Commercial real estate appraisal','Financial'),
('Corporate tax return (C-Corp)','Financial'),
('Credit repair service (monthly)','Financial'),
('Cryptocurrency tax reporting','Financial'),
('Debt consolidation consultation','Financial'),
('Estate plan / wealth transfer plan','Financial'),
('Financial plan creation (CFP)','Financial'),
('Financial statement preparation (monthly)','Financial'),
('Foreign bank account reporting (FBAR)','Financial'),
('Foreign income tax exclusion (FEIE)','Financial'),
('Franchise disclosure review','Financial'),
('Grant writing (nonprofit)','Financial'),
('HSA account setup advice','Financial'),
('Home appraisal','Financial'),
('ITIN application assistance','Financial'),
('Insurance policy review','Financial'),
('Investment portfolio review (per hour)','Financial'),
('Investor pitch deck creation','Financial'),
('Life insurance policy review','Financial'),
('Long-term care insurance analysis','Financial'),
('Medicare enrollment consultation','Financial'),
('Mergers & acquisitions due diligence (per hr)','Financial'),
('Mortgage refinancing assistance','Financial'),
('Non-profit formation (legal + filing)','Financial'),
('Nonprofit 990 filing','Financial'),
('Payroll processing (per employee/month)','Financial'),
('Personal tax return (complex, investments)','Financial'),
('Personal tax return (itemized, schedule C)','Financial'),
('Personal tax return (simple, no itemization)','Financial'),
('QuickBooks setup','Financial'),
('Real estate closing costs (buyer)','Financial'),
('Rental property accounting (annual)','Financial'),
('Retirement planning consultation','Financial'),
('SBA loan application assistance','Financial'),
('Sales tax registration/compliance','Financial'),
('Small business loan application assist','Financial'),
('Social Security benefits analysis','Financial'),
('Tax audit representation','Financial'),
('Archery lesson (per hour)','Fitness'),
('Body composition scan (DEXA)','Fitness'),
('Boxing class (per month)','Fitness'),
('CrossFit class membership (monthly)','Fitness'),
('Cryotherapy session','Fitness'),
('Cycle/spin class (drop-in)','Fitness'),
('Dance fitness class (drop-in)','Fitness'),
('Fitness boot camp (per month)','Fitness'),
('Float therapy / sensory deprivation (1 hr)','Fitness'),
('Golf lesson (per hour)','Fitness'),
('Group fitness class (drop-in)','Fitness'),
('Health DNA/genetic test kit','Fitness'),
('Horseback riding lesson (per hour)','Fitness'),
('Kettlebell class (drop-in)','Fitness'),
('Martial arts class (per month)','Fitness'),
('Meal prep service (weekly)','Fitness'),
('Meditation instructor (per session)','Fitness'),
('Monthly gym membership (basic)','Fitness'),
('Monthly gym membership (premium)','Fitness'),
('Nutritional meal plan creation','Fitness'),
('Personal health assessment','Fitness'),
('Personal training (in-home, 1 hr)','Fitness'),
('Personal training session (gym, 1 hr)','Fitness'),
('Physical fitness assessment','Fitness'),
('Pilates class (group)','Fitness'),
('Pilates private session','Fitness'),
('Private yoga session','Fitness'),
('Qigong class (per month)','Fitness'),
('Recovery/stretch session','Fitness'),
('Rock climbing gym membership (monthly)','Fitness'),
('Sauna session (infrared)','Fitness'),
('Scuba diving lesson (open water cert)','Fitness'),
('Ski lesson (group, half-day)','Fitness'),
('Sleep coaching session','Fitness'),
('Snowboard lesson (private, half-day)','Fitness'),
('Sports massage (60 min)','Fitness'),
('Surf lesson (group)','Fitness'),
('Surf lesson (private)','Fitness'),
('Tai Chi class (per month)','Fitness'),
('Tennis lesson (per hour)','Fitness'),
('VO2 max test','Fitness'),
('Wellness coaching (per session)','Fitness'),
('Yoga class (drop-in)','Fitness'),
('Yoga monthly membership','Fitness'),
('AC air handler replacement','HVAC'),
('AC capacitor replacement','HVAC'),
('AC compressor replacement','HVAC'),
('AC condenser unit replacement','HVAC'),
('AC contactor replacement','HVAC'),
('AC drain line cleaning','HVAC'),
('AC evaporator coil replacement','HVAC'),
('AC refrigerant recharge','HVAC'),
('AC tune-up / maintenance','HVAC'),
('Air filter replacement (standard)','HVAC'),
('Air purifier installation (whole-house)','HVAC'),
('Air scrubber/ionizer installation','HVAC'),
('Attic insulation installation','HVAC'),
('Boiler replacement','HVAC'),
('Boiler service/tune-up','HVAC'),
('Central AC system replacement (full)','HVAC'),
('Crawlspace encapsulation','HVAC'),
('Dryer vent cleaning','HVAC'),
('Duct cleaning (avg home)','HVAC'),
('Duct repair (per section)','HVAC'),
('Duct sealing (full system)','HVAC'),
('Furnace blower motor replacement','HVAC'),
('Furnace heat exchanger replacement','HVAC'),
('Furnace igniter replacement','HVAC'),
('Furnace replacement (gas standard)','HVAC'),
('Furnace replacement (high-efficiency)','HVAC'),
('Furnace tune-up','HVAC'),
('HVAC UV light install (germicidal)','HVAC'),
('Heat pump installation','HVAC'),
('Humidifier installation (whole-house)','HVAC'),
('Mini-split installation (single zone)','HVAC'),
('Oil furnace service','HVAC'),
('Programmable thermostat installation','HVAC'),
('Propane conversion (gas to propane)','HVAC'),
('Radiant floor heating installation (per sq ft)','HVAC'),
('Smart thermostat installation (HVAC)','HVAC'),
('Spray foam attic insulation (full)','HVAC'),
('Spray foam insulation (per 1,000 sq ft)','HVAC'),
('Thermostat replacement (standard)','HVAC'),
('Zone control system setup','HVAC'),
('Acupuncture session','Healthcare'),
('Annual physical exam','Healthcare'),
('Blood panel (basic metabolic)','Healthcare'),
('Blood panel (comprehensive)','Healthcare'),
('Breast augmentation','Healthcare'),
('CBC (complete blood count)','Healthcare'),
('COVID test (rapid, clinic)','Healthcare'),
('CT scan (without insurance)','Healthcare'),
('Chiropractic adjustment','Healthcare'),
('Colonoscopy (without insurance)','Healthcare'),
('Cosmetic Botox (per area)','Healthcare'),
('Dental X-rays (full mouth)','Healthcare'),
('Dental bonding','Healthcare'),
('Dental cleaning + exam (biannual)','Healthcare'),
('Dental crown (per tooth)','Healthcare'),
('Dental filling (composite, per tooth)','Healthcare'),
('Dental implant (full, one tooth)','Healthcare'),
('Dietitian/nutritionist consultation','Healthcare'),
('EKG/ECG (resting)','Healthcare'),
('Emergency room visit (avg without insurance)','Healthcare'),
('Eye exam (comprehensive)','Healthcare'),
('Flu shot','Healthcare'),
('Hair transplant (per graft)','Healthcare'),
('HbA1c test (diabetes)','Healthcare'),
('Hearing aid fitting','Healthcare'),
('Hearing test (audiogram)','Healthcare'),
('Invisalign treatment','Healthcare'),
('Lab drug test (urine)','Healthcare'),
('Lipid panel (cholesterol)','Healthcare'),
('Liposuction (per area)','Healthcare'),
('MRI (without insurance)','Healthcare'),
('Mammogram','Healthcare'),
('Massage therapy (therapeutic, 60 min)','Healthcare'),
('Mental health therapy session (LPC/LCSW)','Healthcare'),
('Occupational therapy session','Healthcare'),
('Orthodontic braces (traditional)','Healthcare'),
('Pap smear/gynecology visit','Healthcare'),
('Personal trainer session (gym)','Healthcare'),
('Physical therapy session','Healthcare'),
('Primary care office visit (without insurance)','Healthcare'),
('Psychiatry consultation','Healthcare'),
('Psychological evaluation','Healthcare'),
('Rhinoplasty (nose job)','Healthcare'),
('Root canal (molar)','Healthcare'),
('STI/STD testing panel','Healthcare'),
('Speech therapy session','Healthcare'),
('Stress test (cardiac)','Healthcare'),
('Teeth whitening (dental office)','Healthcare'),
('Telehealth/virtual visit','Healthcare'),
('Thyroid panel (TSH)','Healthcare'),
('Tooth extraction (simple)','Healthcare'),
('Tooth extraction (surgical/impacted)','Healthcare'),
('Tummy tuck (abdominoplasty)','Healthcare'),
('Ultrasound (diagnostic)','Healthcare'),
('Urgent care visit','Healthcare'),
('Urinalysis','Healthcare'),
('Vaccine (travel, per dose)','Healthcare'),
('Varicose vein treatment (per leg)','Healthcare'),
('Vision correction (LASIK, per eye)','Healthcare'),
('X-ray (chest, single view)','Healthcare'),
('X-ray (extremity)','Healthcare'),
('Attic conversion to living space','Home Repair'),
('Baseboards installation (per linear foot)','Home Repair'),
('Basement finishing (full)','Home Repair'),
('Bathroom remodel (full)','Home Repair'),
('Bathroom remodel (minor)','Home Repair'),
('Bathroom vanity replacement','Home Repair'),
('Bathtub refinishing/reglazing','Home Repair'),
('Bathtub replacement','Home Repair'),
('Carpet cleaning (per room)','Home Repair'),
('Carpet installation (per sq ft)','Home Repair'),
('Closet organizer installation','Home Repair'),
('Crown molding installation (per room)','Home Repair'),
('Drywall installation (per sq ft)','Home Repair'),
('Drywall repair (small hole)','Home Repair'),
('Fireplace insert installation','Home Repair'),
('Fireplace installation (gas, prefab)','Home Repair'),
('Grab bar installation (per bar)','Home Repair'),
('Hardwood floor installation (per sq ft)','Home Repair'),
('Home accessibility ramp install','Home Repair'),
('Home office setup','Home Repair'),
('Interior painting (per room)','Home Repair'),
('Kitchen cabinet installation (full)','Home Repair'),
('Kitchen countertop replacement (granite)','Home Repair'),
('Kitchen countertop replacement (laminate)','Home Repair'),
('Kitchen remodel (major)','Home Repair'),
('Kitchen remodel (minor)','Home Repair'),
('Laminate flooring installation (per sq ft)','Home Repair'),
('Murphy bed installation','Home Repair'),
('Recessed lighting addition (per light)','Home Repair'),
('Room addition (per sq ft)','Home Repair'),
('Safe room / panic room construction','Home Repair'),
('Shower tile replacement','Home Repair'),
('Soundproofing room (per wall, per sq ft)','Home Repair'),
('Stair railing replacement','Home Repair'),
('Stairlift installation','Home Repair'),
('Tile flooring installation (per sq ft)','Home Repair'),
('Walk-in tub installation','Home Repair'),
('Wallpaper installation (per roll)','Home Repair'),
('Wallpaper removal (per room)','Home Repair'),
('Wine cellar conversion','Home Repair'),
('Arborist consultation (per hour)','Landscaping'),
('Artificial turf installation (per sq ft)','Landscaping'),
('Bouldering/rock garden install','Landscaping'),
('Butterfly/pollinator garden','Landscaping'),
('Concrete patio installation (per sq ft)','Landscaping'),
('Dethatching','Landscaping'),
('Drip irrigation installation (per zone)','Landscaping'),
('Fire pit installation','Landscaping'),
('Garden bed creation (per bed)','Landscaping'),
('Grading/leveling yard (per sq ft)','Landscaping'),
('Hedge trimming (per linear foot)','Landscaping'),
('Hydroseeding (per sq ft)','Landscaping'),
('Irrigation system repair','Landscaping'),
('Irrigation/sprinkler system install','Landscaping'),
('Landscape design consultation','Landscaping'),
('Lawn aeration','Landscaping'),
('Lawn fertilization','Landscaping'),
('Lawn maintenance monthly (avg yard)','Landscaping'),
('Lawn mowing (avg yard)','Landscaping'),
('Lawn mowing (large yard)','Landscaping'),
('Leaf removal (seasonal)','Landscaping'),
('Mulching (per cubic yard)','Landscaping'),
('Native plant garden installation','Landscaping'),
('New landscaping installation (avg yard)','Landscaping'),
('Outdoor kitchen installation','Landscaping'),
('Outdoor lighting installation (per fixture)','Landscaping'),
('Overseeding (lawn)','Landscaping'),
('Paver patio installation (per sq ft)','Landscaping'),
('Pergola/trellis installation','Landscaping'),
('Pond installation','Landscaping'),
('Rain garden installation','Landscaping'),
('Retaining wall construction (per sq ft)','Landscaping'),
('Shrub trimming (per shrub)','Landscaping'),
('Snow plowing (per visit)','Landscaping'),
('Snow removal (per hour)','Landscaping'),
('Sod installation (per sq ft)','Landscaping'),
('Sod repair (small area)','Landscaping'),
('Stump grinding','Landscaping'),
('Tree removal (large, over 60 ft)','Landscaping'),
('Tree removal (small, under 30 ft)','Landscaping'),
('Tree trimming (large tree)','Landscaping'),
('Tree trimming (small tree)','Landscaping'),
('Weed barrier installation (per sq ft)','Landscaping'),
('Weed control treatment','Landscaping'),
('Xeriscape/drought-resistant landscape','Landscaping'),
('Attorney consultation (1 hour)','Legal'),
('Bankruptcy filing (Chapter 13)','Legal'),
('Bankruptcy filing (Chapter 7)','Legal'),
('Business formation (LLC)','Legal'),
('Cease and desist letter drafting','Legal'),
('Child custody agreement','Legal'),
('Citizenship/naturalization application','Legal'),
('Contract drafting (simple)','Legal'),
('Contract review (per hour)','Legal'),
('Copyright registration (attorney fee)','Legal'),
('Criminal defense (felony)','Legal'),
('Criminal defense (misdemeanor)','Legal'),
('Criminal record expungement','Legal'),
('DUI/DWI defense','Legal'),
('Divorce (contested)','Legal'),
('Divorce (uncontested, simple)','Legal'),
('Document apostille','Legal'),
('Employment discrimination case','Legal'),
('Estate probate (attorney, simple)','Legal'),
('Eviction filing/landlord representation','Legal'),
('Guardianship petition','Legal'),
('Healthcare directive/living will','Legal'),
('Immigration visa application (attorney)','Legal'),
('Juvenile record expungement','Legal'),
('Living trust creation','Legal'),
('Name change petition','Legal'),
('Non-compete agreement review','Legal'),
('Non-disclosure agreement (NDA)','Legal'),
('Notarization (per signature)','Legal'),
('Operating agreement (LLC)','Legal'),
('Partnership agreement drafting','Legal'),
('Patent application (provisional)','Legal'),
('Patent application (utility, attorney fee)','Legal'),
('Personal injury claim (contingency)','Legal'),
('Power of attorney document','Legal'),
('Prenuptial agreement','Legal'),
('Real estate closing (attorney fee)','Legal'),
('Shareholder agreement','Legal'),
('Simple will drafting','Legal'),
('Small claims court filing assistance','Legal'),
('Tenant rights consultation','Legal'),
('Title search (real estate)','Legal'),
('Trademark registration (attorney fee)','Legal'),
('Traffic ticket defense','Legal'),
('Worker''s comp claim assistance','Legal'),
('Antique/artwork crating (per piece)','Moving'),
('Art/antique moving (specialty)','Moving'),
('Auto shipping (open carrier)','Moving'),
('Boat transport (per mile)','Moving'),
('Climate-controlled storage (premium)','Moving'),
('College move-in/move-out service','Moving'),
('Corporate relocation package','Moving'),
('Cross-country move (avg 2-BR)','Moving'),
('Downsizing/senior move management','Moving'),
('Estate cleanout service','Moving'),
('File/document shredding (per box)','Moving'),
('Full-service moving (military relocation)','Moving'),
('Furniture assembly (per piece)','Moving'),
('Furniture delivery assembly (flat-rate)','Moving'),
('Furniture disassembly','Moving'),
('Furniture liquidation service','Moving'),
('International moving estimate/planning','Moving'),
('Junk hauling (per cubic yard)','Moving'),
('Junk removal (single item pickup)','Moving'),
('Local move (2 movers, 2 hours min)','Moving'),
('Local move (full home, avg)','Moving'),
('Long-distance move (per lb + distance)','Moving'),
('Move-out cleaning (apartment)','Moving'),
('Moving insurance (full-value protection)','Moving'),
('Packing service (full home)','Moving'),
('Partial packing service','Moving'),
('Piano moving (grand)','Moving'),
('Piano moving (upright)','Moving'),
('Portable storage container rental (per month)','Moving'),
('Record storage (per box/month)','Moving'),
('Storage unit (10x10, monthly)','Moving'),
('Storage unit (10x20, monthly)','Moving'),
('Storage unit (5x5, monthly)','Moving'),
('Vehicle transport (coast to coast)','Moving'),
('Air quality testing (home)','Pest Control'),
('Ant treatment (interior)','Pest Control'),
('Appliance repair (dishwasher)','Pest Control'),
('Appliance repair (dryer)','Pest Control'),
('Appliance repair (microwave)','Pest Control'),
('Appliance repair (oven/range)','Pest Control'),
('Appliance repair (refrigerator)','Pest Control'),
('Appliance repair (washing machine)','Pest Control'),
('Asbestos testing','Pest Control'),
('Attic restoration (after pest damage)','Pest Control'),
('Bat exclusion service','Pest Control'),
('Bed bug treatment (chemical, whole home)','Pest Control'),
('Bed bug treatment (heat, per room)','Pest Control'),
('Bird control installation','Pest Control'),
('Chimney animal removal','Pest Control'),
('Cockroach treatment','Pest Control'),
('Crawlspace vapor barrier install','Pest Control'),
('Dryer drum repair','Pest Control'),
('Flea treatment (full home)','Pest Control'),
('General pest control (one-time)','Pest Control'),
('General pest control (quarterly plan)','Pest Control'),
('Gopher/mole removal','Pest Control'),
('Home energy audit','Pest Control'),
('Insulation audit','Pest Control'),
('Key duplication','Pest Control'),
('Lawn fungicide treatment','Pest Control'),
('Lead paint testing','Pest Control'),
('Locksmith (lockout service)','Pest Control'),
('Mosquito treatment (yard, per visit)','Pest Control'),
('Mosquito yard treatment (season plan)','Pest Control'),
('Radon mitigation system install','Pest Control'),
('Rodent control (mice/rats)','Pest Control'),
('Safe installation/mounting','Pest Control'),
('Septic alarm repair','Pest Control'),
('Skunk removal/odor treatment','Pest Control'),
('Smart lock installation (per lock)','Pest Control'),
('Snake removal','Pest Control'),
('Termite inspection','Pest Control'),
('Termite treatment (spot/liquid)','Pest Control'),
('Termite treatment (whole-house fumigation)','Pest Control'),
('Tick yard treatment','Pest Control'),
('Wasp/bee nest removal','Pest Control'),
('Water heater descaling (tankless)','Pest Control'),
('Water quality testing (well)','Pest Control'),
('Wildlife removal (raccoon/squirrel)','Pest Control'),
('Aquarium maintenance (monthly service)','Pet Care'),
('Aquarium setup service (custom)','Pet Care'),
('Bird grooming (per visit)','Pet Care'),
('Cat behavioral consultation','Pet Care'),
('Cat boarding (per night)','Pet Care'),
('Cat grooming','Pet Care'),
('Cat spay/neuter','Pet Care'),
('Dog agility training (per class)','Pet Care'),
('Dog behavioral consultation','Pet Care'),
('Dog boarding (per night)','Pet Care'),
('Dog daycare (per day)','Pet Care'),
('Dog grooming (large breed full groom)','Pet Care'),
('Dog grooming (small breed bath/trim)','Pet Care'),
('Dog spay/neuter','Pet Care'),
('Dog training (group class, per session)','Pet Care'),
('Dog training (private session)','Pet Care'),
('Dog walking (30 min)','Pet Care'),
('Emergency vet visit','Pet Care'),
('Heartworm test + treatment (if positive)','Pet Care'),
('Horse farrier (trim + shoe, per horse)','Pet Care'),
('Livestock large animal vet visit','Pet Care'),
('Pet burial (cemetery)','Pet Care'),
('Pet cremation (dog)','Pet Care'),
('Pet dental cleaning','Pet Care'),
('Pet first aid class','Pet Care'),
('Pet insurance (monthly, dog)','Pet Care'),
('Pet microchipping','Pet Care'),
('Pet sitting (in-home, per day)','Pet Care'),
('Pet transportation service','Pet Care'),
('Pet vaccinations (per vaccine)','Pet Care'),
('Service animal training program','Pet Care'),
('Veterinary wellness exam','Pet Care'),
('Animated explainer video (per minute)','Photography'),
('Brand photography package (full day)','Photography'),
('Brand/commercial shoot (half day)','Photography'),
('Copywriting (blog post, 1,000 words)','Photography'),
('Drone videography session','Photography'),
('Family photo session (1.5 hours)','Photography'),
('Ghostwriting (book, per word)','Photography'),
('Headshot session (professional)','Photography'),
('Infographic design','Photography'),
('Live streaming setup (event)','Photography'),
('Maternity photo session','Photography'),
('Music video production (indie)','Photography'),
('Newborn photography session','Photography'),
('Newsletter writing (per issue)','Photography'),
('Photo colorization (per photo)','Photography'),
('Photo restoration (old/damaged photo)','Photography'),
('Podcast cover art design','Photography'),
('Podcast editing (per episode)','Photography'),
('Podcast launch package','Photography'),
('Podcast recording (per episode)','Photography'),
('Portrait session (1 hour)','Photography'),
('Press release writing','Photography'),
('Product photography (per product)','Photography'),
('Proofreading (per 1,000 words)','Photography'),
('Real estate photo shoot (standard home)','Photography'),
('Short film production (per day)','Photography'),
('Social media content creation (monthly)','Photography'),
('Transcription (per audio hour)','Photography'),
('Translation (per word)','Photography'),
('Video production (corporate, 2-min)','Photography'),
('Voice-over recording (per minute)','Photography'),
('YouTube channel audit & strategy','Photography'),
('YouTube video editing (per minute)','Photography'),
('Backflow preventer installation','Plumbing'),
('Bathtub drain repair','Plumbing'),
('Bathtub installation (standard)','Plumbing'),
('Burst pipe repair (emergency)','Plumbing'),
('Dishwasher hookup (water/drain)','Plumbing'),
('Dishwasher installation','Plumbing'),
('Drain cleaning (main sewer line)','Plumbing'),
('Drain cleaning (sink/tub)','Plumbing'),
('Expansion tank installation','Plumbing'),
('Faucet repair (dripping)','Plumbing'),
('Faucet replacement (standard)','Plumbing'),
('Garbage disposal installation','Plumbing'),
('Garbage disposal repair','Plumbing'),
('Gas line installation (new)','Plumbing'),
('Gas line repair/connection','Plumbing'),
('Hydrojetting (sewer line)','Plumbing'),
('Ice maker water line install','Plumbing'),
('Kitchen faucet installation','Plumbing'),
('Leak detection (non-invasive)','Plumbing'),
('Outdoor spigot/hose bib replacement','Plumbing'),
('Pipe insulation (per linear foot)','Plumbing'),
('Pipe repair (small section)','Plumbing'),
('Pipe replacement (per linear foot)','Plumbing'),
('Pressure test (plumbing system)','Plumbing'),
('Septic system inspection','Plumbing'),
('Septic tank pumping','Plumbing'),
('Sewer line replacement (per foot)','Plumbing'),
('Shower faucet/valve replacement','Plumbing'),
('Shower pan replacement','Plumbing'),
('Showerhead replacement','Plumbing'),
('Sink installation (bathroom)','Plumbing'),
('Sink installation (kitchen)','Plumbing'),
('Sump pump installation','Plumbing'),
('Sump pump replacement','Plumbing'),
('Tankless water heater installation','Plumbing'),
('Toilet repair (flapper/fill valve)','Plumbing'),
('Toilet replacement','Plumbing'),
('Toilet unclogging','Plumbing'),
('Trenchless pipe lining','Plumbing'),
('Under-sink water filter install','Plumbing'),
('Video camera sewer inspection','Plumbing'),
('Washing machine hookup','Plumbing'),
('Water heater repair','Plumbing'),
('Water heater replacement (tank, 40 gal)','Plumbing'),
('Water main shutoff valve replacement','Plumbing'),
('Water meter replacement (coord with utility)','Plumbing'),
('Water pressure regulator replacement','Plumbing'),
('Water softener installation','Plumbing'),
('Whole-house re-pipe (copper, per sq ft)','Plumbing'),
('Whole-house water filtration install','Plumbing'),
('3D virtual tour (Matterport)','Real Estate'),
('Aerial/drone real estate photography','Real Estate'),
('Buyer''s agent negotiation coaching','Real Estate'),
('Commercial real estate broker (lease)','Real Estate'),
('Comparative market analysis (CMA)','Real Estate'),
('Deed preparation','Real Estate'),
('Escrow fee (closing)','Real Estate'),
('Eviction process service','Real Estate'),
('Foreclosure defense','Real Estate'),
('Full home staging service','Real Estate'),
('HOA management service (per unit/month)','Real Estate'),
('Home inspection (standard, 2,000 sq ft)','Real Estate'),
('Home staging consultation','Real Estate'),
('Investment property analysis','Real Estate'),
('Land survey (topographic)','Real Estate'),
('Landlord-tenant dispute mediation','Real Estate'),
('Lease agreement drafting','Real Estate'),
('Mold inspection','Real Estate'),
('Pest/termite inspection','Real Estate'),
('Pool inspection','Real Estate'),
('Property management (residential, per month)','Real Estate'),
('Property tax appeal assistance','Real Estate'),
('Radon testing','Real Estate'),
('Real estate agent buyer representation','Real Estate'),
('Real estate agent commission (seller, ~5-6%)','Real Estate'),
('Real estate photography (standard home)','Real Estate'),
('Real estate transaction coordinator','Real Estate'),
('Rent-to-own contract setup','Real Estate'),
('Rental market analysis report','Real Estate'),
('Security deposit escrow service','Real Estate'),
('Sewer scope inspection','Real Estate'),
('Short sale negotiation (attorney)','Real Estate'),
('Survey (boundary, residential)','Real Estate'),
('Tenant screening service','Real Estate'),
('Title insurance (owner''s policy)','Real Estate'),
('Asphalt shingle repair (per square)','Roofing'),
('Balcony waterproofing','Roofing'),
('Carport installation','Roofing'),
('Chimney cap installation','Roofing'),
('Chimney flashing repair','Roofing'),
('Chimney liner replacement','Roofing'),
('Chimney repair (tuckpointing)','Roofing'),
('Concrete leveling (mudjacking, per sq ft)','Roofing'),
('Deck building (pressure-treated, 200 sq ft)','Roofing'),
('Deck repair','Roofing'),
('Deck staining/sealing','Roofing'),
('Door installation (interior)','Roofing'),
('Door replacement (exterior, standard)','Roofing'),
('Downspout repair/replacement','Roofing'),
('Driveway crack repair','Roofing'),
('Driveway sealing (asphalt)','Roofing'),
('Exterior painting (per sq ft)','Roofing'),
('Fence installation (per linear foot)','Roofing'),
('Fence repair (per section)','Roofing'),
('Foundation crack repair (per crack)','Roofing'),
('Foundation repair (slab, per pier)','Roofing'),
('Full foundation repair (avg)','Roofing'),
('Full roof replacement (asphalt, 1,500 sq ft)','Roofing'),
('Full roof replacement (premium materials)','Roofing'),
('Garage door opener installation','Roofing'),
('Garage door repair','Roofing'),
('Garage door replacement','Roofing'),
('Gutter repair','Roofing'),
('Gutter replacement (avg home)','Roofing'),
('New concrete driveway (per sq ft)','Roofing'),
('Pergola installation','Roofing'),
('Pool deck resurfacing (per sq ft)','Roofing'),
('Pressure washing (per sq ft)','Roofing'),
('Ridge vent installation (per linear foot)','Roofing'),
('Roof inspection','Roofing'),
('Sidewalk repair (per linear foot)','Roofing'),
('Siding repair (per section)','Roofing'),
('Skylight installation','Roofing'),
('Soffit/fascia repair','Roofing'),
('Structural foundation lift/level','Roofing'),
('Vinyl siding replacement (full home)','Roofing'),
('Window replacement (per window)','Roofing'),
('Wood siding replacement','Roofing'),
('3D printing service (per hour)','Tech Support'),
('API integration (simple)','Tech Support'),
('App development (simple mobile app)','Tech Support'),
('Chatbot setup (website)','Tech Support'),
('Cloud setup (Google Workspace/M365)','Tech Support'),
('Computer diagnostics','Tech Support'),
('Computer tune-up/optimization','Tech Support'),
('Custom software development (per hour)','Tech Support'),
('Cybersecurity assessment','Tech Support'),
('Cybersecurity monitoring (per month)','Tech Support'),
('Data backup setup','Tech Support'),
('Data destruction (certified, per drive)','Tech Support'),
('Data recovery (failed drive)','Tech Support'),
('Data recovery (functional drive)','Tech Support'),
('Database migration','Tech Support'),
('Desktop HDD/SSD replacement','Tech Support'),
('Desktop RAM upgrade (install)','Tech Support'),
('Domain registration + hosting setup','Tech Support'),
('Drone photography session','Tech Support'),
('Email list migration','Tech Support'),
('Email migration/setup','Tech Support'),
('Game console repair (disc drive/HDMI)','Tech Support'),
('Graphic design (per hour)','Tech Support'),
('Home networking (cable runs, per drop)','Tech Support'),
('Home theater setup (audio/video)','Tech Support'),
('IT support (on-site, per hour)','Tech Support'),
('IT support (remote, per hour)','Tech Support'),
('Laptop battery replacement','Tech Support'),
('Laptop keyboard replacement','Tech Support'),
('Laptop screen replacement','Tech Support'),
('Logo design','Tech Support'),
('Managed IT services (small biz/month)','Tech Support'),
('NAS (network attached storage) setup','Tech Support'),
('NVR/DVR setup','Tech Support'),
('Network setup (home WiFi)','Tech Support'),
('OS reinstallation (Windows/Mac)','Tech Support'),
('POS system setup (retail/restaurant)','Tech Support'),
('Password manager setup','Tech Support'),
('Photo editing (per photo)','Tech Support'),
('Printer repair','Tech Support'),
('Printer setup/configuration','Tech Support'),
('SEO audit (website)','Tech Support'),
('Security camera installation (per camera)','Tech Support'),
('Server setup (small business)','Tech Support'),
('Smart home device setup (per device)','Tech Support'),
('Smart home system integration','Tech Support'),
('Smartphone battery replacement','Tech Support'),
('Smartphone screen replacement (Android)','Tech Support'),
('Smartphone screen replacement (iPhone)','Tech Support'),
('Social media account setup (full kit)','Tech Support'),
('Software installation (per program)','Tech Support'),
('TV mounting (above fireplace)','Tech Support'),
('TV mounting (standard wall)','Tech Support'),
('Tablet screen repair','Tech Support'),
('VPN setup (home/business)','Tech Support'),
('Video editing (per minute of output)','Tech Support'),
('Virus/malware removal','Tech Support'),
('Website design (basic, 5-page)','Tech Support'),
('Website design (ecommerce)','Tech Support'),
('WiFi router installation/config','Tech Support'),
('WordPress site setup','Tech Support')
ON CONFLICT (name) DO NOTHING;

-- ─── 500 New Licenses ──────────────────────────────────────────────────────

INSERT INTO licenses_lookup (name, category) VALUES
('ASE Advanced Engine Performance L1','Auto'),
('ASE Drivetrain A3 Certification','Auto'),
('ASE Engine Machinist C1','Auto'),
('ASE Exhaust Systems Certification','Auto'),
('ASE Manual Drive Train A3','Auto'),
('ASE Medium/Heavy Truck Certification','Auto'),
('ASE School Bus Certification','Auto'),
('ASE Suspension & Steering A4','Auto'),
('ASE Transit Bus Certification','Auto'),
('Auto Air Conditioning Certification (MACS)','Auto'),
('Auto Auction License','Auto'),
('Auto Body Damage Estimator Certification','Auto'),
('Auto Refinishing Technician Certification','Auto'),
('Automotive Dealer License','Auto'),
('Automotive Fleet Manager Certification','Auto'),
('Automotive Locksmith Certification','Auto'),
('Automotive Parts Specialist Certification','Auto'),
('Automotive Service Advisor Certification (ASE)','Auto'),
('Automotive Service Excellence Master Truck Technician','Auto'),
('Automotive Technology Associate Degree','Auto'),
('CDL Air Brakes Endorsement','Auto'),
('Classic Car Restoration Technician Certification','Auto'),
('EPA 609 MVAC Certification','Auto'),
('Marine Engine Technician Certification','Auto'),
('Mobile Auto Glass Installer Certification','Auto'),
('Motorcycle Technician Certification (MMI)','Auto'),
('NADA Certified Used Car Appraiser','Auto'),
('PTEN Certified Auto Detailer','Auto'),
('Powersports Technician Certification (PSTN)','Auto'),
('RV Technician Certification (RVIA)','Auto'),
('Smog Check Inspector License','Auto'),
('Tire Industry Association Technician Certification','Auto'),
('Transmission Rebuild Certification','Auto'),
('Acrylic Nail Technician Certification','Beauty'),
('Airbrush Tanning Technician Certification','Beauty'),
('Body Piercing Technician License','Beauty'),
('Body Wrap Technician Certification','Beauty'),
('Brow Lamination Technician Certification','Beauty'),
('Certified Professional Makeup Artist (PMI)','Beauty'),
('Gel Nail Technician Certification','Beauty'),
('Hair Extension Specialist Certification','Beauty'),
('Holistic Skin Care Practitioner Certification','Beauty'),
('Keratin Treatment Specialist Certification','Beauty'),
('Nail Art Specialist Certification','Beauty'),
('Pedicure Specialty Certification','Beauty'),
('SFX Makeup Artist Certification','Beauty'),
('Scalp Micropigmentation Technician Certification','Beauty'),
('Skin Care Specialist Certification (CIDesco)','Beauty'),
('Sugar Waxing Certification','Beauty'),
('Tattoo Artist License','Beauty'),
('Tattoo Removal Technician License','Beauty'),
('Threading Technician Certification','Beauty'),
('Trichology Certification','Beauty'),
('Waxing Specialist Certification','Beauty'),
('Air Duct Cleaning Specialist Certification (NADCA)','Cleaning'),
('Applied Structural Drying Technician (ASD)','Cleaning'),
('Asbestos Abatement Worker License','Cleaning'),
('Biohazard Remediation Technician Certification','Cleaning'),
('Certified Building Service Executive (CBSE)','Cleaning'),
('Certified Cleaning Technician (ISSA)','Cleaning'),
('Certified Mold Remediation Contractor','Cleaning'),
('Commercial Kitchen Hood Cleaning Certification (IKECA)','Cleaning'),
('Crime Scene Cleanup Technician Certification','Cleaning'),
('Fire and Smoke Damage Restoration Certification','Cleaning'),
('Healthcare Housekeeping Certification (CHEST)','Cleaning'),
('IICRC Carpet Cleaning Technician Certification','Cleaning'),
('IICRC Upholstery Cleaning Technician Certification','Cleaning'),
('Janitorial Supervisor Certification','Cleaning'),
('Lead Paint Abatement Worker License','Cleaning'),
('OSHA Bloodborne Pathogen Training Certificate','Cleaning'),
('Pool and Spa Service Technician License','Cleaning'),
('Pressure Washing Contractor License','Cleaning'),
('Restoration Industry Association Certification (RIA)','Cleaning'),
('Trauma Scene Practitioner Certification','Cleaning'),
('Water Damage Restoration Technician (WRT)','Cleaning'),
('Adult Education Instructor Certification','Education'),
('Art Education Teaching License','Education'),
('Autism Specialist Certification','Education'),
('Bilingual Education Teaching Certification','Education'),
('Board Certified Behavior Analyst Assistant (BCaBA)','Education'),
('Career and Technical Education (CTE) License','Education'),
('Certified Learning Disability Specialist','Education'),
('Chess Instructor Certification (USCF)','Education'),
('Drama Coach Certification','Education'),
('Google Certified Educator Level 2','Education'),
('Gymnastics Coach Certification (USAG)','Education'),
('Martial Arts Instructor Certification','Education'),
('Math Specialist Certification','Education'),
('Microsoft Certified Educator (MCE)','Education'),
('Music Education Teaching License','Education'),
('Online Instructor Certification','Education'),
('Physical Education Teaching License','Education'),
('School Administrator License','Education'),
('School Counselor License','Education'),
('School Library Media Specialist License','Education'),
('School Psychologist License','Education'),
('School Social Worker License','Education'),
('Science Specialist Certification','Education'),
('Secondary Education Teaching License','Education'),
('Superintendent License','Education'),
('Swimming Instructor Certification (Red Cross)','Education'),
('Vocational Education Instructor License','Education'),
('Arc Flash Safety Certification (NFPA 70E)','Electrical'),
('BICSI Installer Technician Certification','Electrical'),
('Certified Electrical Inspector (CEI)','Electrical'),
('Certified Electrical Test Technician (NETA)','Electrical'),
('Data Center Electrician Certification','Electrical'),
('Electrical Apprentice Registration','Electrical'),
('Electrical Contractor Qualifier License','Electrical'),
('Electrical Inspector License','Electrical'),
('Electrical Journeyman License (Commercial)','Electrical'),
('Electrical Plan Examiner License','Electrical'),
('Elevator Electrician License','Electrical'),
('Energy Storage Technician Certification','Electrical'),
('Home Automation Electrician Certification','Electrical'),
('Marine Electrician Certification (ABYC)','Electrical'),
('National Electrical Code (NEC) Certification','Electrical'),
('OSHA 30 Electrical Safety','Electrical'),
('Photovoltaic Installer Certification (NABCEP PV)','Electrical'),
('Photovoltaic Systems Designer Certification','Electrical'),
('Smart Grid Technician Certification','Electrical'),
('Solar Electrical Contractor License','Electrical'),
('Theater Electrician Certification','Electrical'),
('Wind Turbine Electrician Certification','Electrical'),
('Audio Visual Technician Certification (AVIXA)','Events'),
('Banquet Captain Certification','Events'),
('Bounce House and Inflatable Operator Certification','Events'),
('Catering Manager Certification','Events'),
('Certified Event Designer (CED)','Events'),
('Certified Meeting Manager (CMM)','Events'),
('Certified Meeting Professional (CMP)','Events'),
('Certified Special Events Professional (CSEP)','Events'),
('Civil Wedding Officiant Certification','Events'),
('Event Security Certification (ASIS)','Events'),
('Event Tent Installer Certification','Events'),
('Floral Designer Certification (AIF)','Events'),
('Food Safety Manager for Events Certification','Events'),
('Food Truck Operator License','Events'),
('Licensed Auctioneer','Events'),
('Lighting Technician Certification (ETC)','Events'),
('Notary Public Officiant Certification','Events'),
('Production Assistant Certification','Events'),
('Professional DJ Certification (NAMM)','Events'),
('Stage Manager Certification','Events'),
('Wedding Planner Certification (WPIC)','Events'),
('Accredited Financial Counselor (AFC)','Financial'),
('Accredited Investment Fiduciary (AIF)','Financial'),
('Accredited in Business Valuation (ABV)','Financial'),
('Certified Business Appraiser (CBA)','Financial'),
('Certified Credit Counselor (CCC)','Financial'),
('Certified Exit Planning Advisor (CEPA)','Financial'),
('Certified Government Financial Manager (CGFM)','Financial'),
('Certified Internal Auditor (CIA)','Financial'),
('Certified Long-Term Care (CLTC)','Financial'),
('Certified Management Accountant (CMA)','Financial'),
('Certified Public Finance Officer (CPFO)','Financial'),
('Certified Retirement Counselor (CRC)','Financial'),
('Certified Treasury Professional (CTP)','Financial'),
('Certified Valuation Analyst (CVA)','Financial'),
('Chartered Alternative Investment Analyst (CAIA)','Financial'),
('Chartered Financial Analyst (CFA)','Financial'),
('Chartered Life Underwriter (CLU)','Financial'),
('Estate Planning Law Specialist Certification','Financial'),
('FINRA Series 6 License','Financial'),
('FINRA Series 66 License','Financial'),
('FINRA Series 79 Investment Banking','Financial'),
('Financial Risk Manager (FRM)','Financial'),
('Housing Counselor Certification (HUD)','Financial'),
('Insurance Agent License (Life & Health)','Financial'),
('Insurance Agent License (Property & Casualty)','Financial'),
('Registered Investment Adviser License (RIA)','Financial'),
('Surplus Lines Insurance Broker License','Financial'),
('Certified Functional Movement Specialist (FMS)','Fitness'),
('Certified Personal Trainer (NSCA)','Fitness'),
('Certified Strength and Conditioning Specialist (CSCS)','Fitness'),
('Certified Wellness Coach (NWI)','Fitness'),
('Corrective Exercise Specialist (ACE)','Fitness'),
('Corrective Holistic Exercise Kinesiologist (CHEK)','Fitness'),
('CrossFit Level 1 Trainer Certification','Fitness'),
('CrossFit Level 2 Trainer Certification','Fitness'),
('Cycling Instructor Certification (Spinning)','Fitness'),
('Group Fitness Instructor Certification (ACE)','Fitness'),
('Group Fitness Instructor Certification (AFAA)','Fitness'),
('Health Coach Certification (NCHEC)','Fitness'),
('ISSA Specialist in Fitness Nutrition','Fitness'),
('Kettlebell Instructor Certification (SFG)','Fitness'),
('Les Mills Certified Instructor','Fitness'),
('Precision Nutrition Level 1 Certification','Fitness'),
('Swim Coach Certification (ASCA)','Fitness'),
('TRX Suspension Training Certification','Fitness'),
('USA Track & Field Coach Certification','Fitness'),
('USA Weightlifting Coach Certification','Fitness'),
('Zumba Instructor License','Fitness'),
('ASHRAE Building Energy Assessor Certification','HVAC'),
('Air Balancing Technician Certification (TABB)','HVAC'),
('Boiler Inspector License','HVAC'),
('Chiller Technician Certification','HVAC'),
('Combustion Analyst Certification (BPI)','HVAC'),
('EPA 608 Type I CFC Certification','HVAC'),
('EPA 608 Type II HCFC Certification','HVAC'),
('EPA 608 Type III Low Pressure Certification','HVAC'),
('Geothermal Heat Pump Installer Certification','HVAC'),
('HVAC Controls Technician Certification','HVAC'),
('High Pressure Boiler Operator License','HVAC'),
('Indoor Air Quality Professional Certification','HVAC'),
('Industrial Refrigeration Operator License','HVAC'),
('NATE Air Distribution Service Certification','HVAC'),
('NATE Commercial Refrigeration Certification','HVAC'),
('NATE Oil Heating Service Certification','HVAC'),
('Propane Gas Technician Certification','HVAC'),
('RSES Certified Refrigeration Service Technician','HVAC'),
('Refrigeration Contractor License','HVAC'),
('Sheet Metal Contractor License','HVAC'),
('Sheet Metal Journeyman License','HVAC'),
('VRF/VRV Systems Technician Certification','HVAC'),
('Addiction Counselor Certification (CAC)','Healthcare'),
('Athletic Trainer Certification (ATC)','Healthcare'),
('Audiologist License','Healthcare'),
('Certified Nurse Midwife (CNM)','Healthcare'),
('Certified Peer Support Specialist','Healthcare'),
('Certified Surgical Technologist (CST)','Healthcare'),
('Corrective Exercise Specialist Certification (NASM)','Healthcare'),
('Dental Assistant Certification (CDA)','Healthcare'),
('Dental Hygienist License (RDH)','Healthcare'),
('Diagnostic Medical Sonographer Certification (RDMS)','Healthcare'),
('Doctor of Medicine License (MD)','Healthcare'),
('Doctor of Osteopathy License (DO)','Healthcare'),
('Health Information Technician Certification (RHIT)','Healthcare'),
('Hypnotherapy Certification (CHt)','Healthcare'),
('Medical Billing and Coding Certification','Healthcare'),
('Nuclear Medicine Technologist Certification','Healthcare'),
('Nurse Practitioner License (APRN)','Healthcare'),
('Optometry License (OD)','Healthcare'),
('Physician Assistant License (PA)','Healthcare'),
('Pilates Instructor Certification (PMA)','Healthcare'),
('Radiologic Technologist License (RT)','Healthcare'),
('Reflexology Practitioner Certification','Healthcare'),
('Reiki Master Certification','Healthcare'),
('Respiratory Therapist License (CRT)','Healthcare'),
('Sleep Technologist Certification (RPSGT)','Healthcare'),
('Sports Nutrition Certification (CISSN)','Healthcare'),
('Yoga Therapy Certification (C-IAYT)','Healthcare'),
('Cabinet Maker Certification (AWI)','Home Repair'),
('Carpet Installer Certification (CFI)','Home Repair'),
('Ceramic Tile Installer Certification','Home Repair'),
('Certified Kitchen and Bath Remodeler (NKBA)','Home Repair'),
('Door and Hardware Installer Certification (DHI)','Home Repair'),
('Foundation Repair Technician Certification','Home Repair'),
('Glass Installer Certification (NGA)','Home Repair'),
('Glazier Journeyman License','Home Repair'),
('Hardwood Floor Inspector Certification (NWFA)','Home Repair'),
('Hardwood Floor Installation Certification (NWFA)','Home Repair'),
('Home Performance Specialist Certification (BPI)','Home Repair'),
('ICC Accessibility Inspector Certification','Home Repair'),
('ICC Building Inspector Certification','Home Repair'),
('ICC Residential Combination Inspector','Home Repair'),
('Lead Paint Renovator Certification (RRP)','Home Repair'),
('Marble and Granite Installer Certification','Home Repair'),
('Paint Applicator Certification','Home Repair'),
('Residential Energy Auditor Certification','Home Repair'),
('Residential Remodeling Contractor License','Home Repair'),
('Residential Structural Inspector License','Home Repair'),
('Stone Installer Certification','Home Repair'),
('Terrazzo Finisher Certification','Home Repair'),
('Tile Setter Certification (CTI)','Home Repair'),
('Universal Design Certified Professional (UDCP)','Home Repair'),
('Waterproofing Specialist Certification','Home Repair'),
('Weatherization Technician Certification','Home Repair'),
('Window Film Installer Certification (IWFA)','Home Repair'),
('Aerial Lift Tree Worker Certification','Landscaping'),
('Aquatic Pesticide Applicator License','Landscaping'),
('Arborist Apprentice Certification','Landscaping'),
('Certified Grounds Manager (CGM)','Landscaping'),
('Certified Irrigation Designer (CID)','Landscaping'),
('Certified Landscape Professional (CLP)','Landscaping'),
('Certified Landscape Technician (CLT)','Landscaping'),
('Certified Nursery Professional (CNP)','Landscaping'),
('Golf Course Superintendent Certification (CGCS)','Landscaping'),
('Green Roof Installer Certification','Landscaping'),
('Hardscape Technician Certification (ICPI)','Landscaping'),
('Horticulture Certified Professional (HCP)','Landscaping'),
('Hunter Certified Irrigation Designer','Landscaping'),
('Irrigation Association Landscape Water Management Certification','Landscaping'),
('Landscape Architect License (RLA)','Landscaping'),
('Landscape Contractor License','Landscaping'),
('Landscape Industry Certified Ornamental Maintenance','Landscaping'),
('Outdoor Lighting Specialist Certification (AOLP)','Landscaping'),
('Pesticide Applicator License (Lawn)','Landscaping'),
('Rain Bird Certified Irrigation Contractor','Landscaping'),
('Segmental Retaining Wall Installer (SRW)','Landscaping'),
('Snow and Ice Professional Certification (SIMA)','Landscaping'),
('Soil Scientist Certification','Landscaping'),
('Sports Field Manager Certification (CSFM)','Landscaping'),
('Tree Risk Assessment Qualified (TRAQ)','Landscaping'),
('Turfgrass Science Certification','Landscaping'),
('Utility Arborist Certification (UAA)','Landscaping'),
('Attorney at Law License (JD)','Legal'),
('Bankruptcy Law Specialist Certification','Legal'),
('Certified Contract Manager (CCM)','Legal'),
('Certified Court Reporter (CCR)','Legal'),
('Certified Immigration Specialist','Legal'),
('Certified Intellectual Property Professional','Legal'),
('Certified Paralegal (CP)','Legal'),
('Certified Regulatory Compliance Manager','Legal'),
('Certified Translator (ATA)','Legal'),
('Compliance Officer Certification (CCO)','Legal'),
('Contract Attorney Certification','Legal'),
('Court Interpreter Certification','Legal'),
('Elder Law Attorney Certification (CELA)','Legal'),
('Employment Law Certificate','Legal'),
('Environmental Compliance Inspector Certification','Legal'),
('Family Law Facilitator Certification','Legal'),
('Legal Document Preparer License','Legal'),
('Licensed Clinical Social Worker (LCSW)','Legal'),
('Licensed Immigration Consultant','Legal'),
('Licensed Professional Counselor (LPC)','Legal'),
('Marriage and Family Therapist License (MFT)','Legal'),
('Privacy Law Specialist Certification','Legal'),
('Process Server License','Legal'),
('Registered Legal Nurse Consultant (RLNC)','Legal'),
('State Bar Admission License','Legal'),
('Title Insurance Agent License','Legal'),
('Victim Advocate Certification','Legal'),
('Aerial Work Platform Certification (IPAF)','Moving'),
('Certified Moving Consultant (CMC)','Moving'),
('Commercial Cargo Carrier License','Moving'),
('Commercial Van Line Agent Certification','Moving'),
('Crane Safety Certification (NCCCO)','Moving'),
('Fine Art Packer and Mover Certification','Moving'),
('Hoisting and Rigging Safety Certification','Moving'),
('Licensed Household Goods Mover (FMCSA)','Moving'),
('Logistics Manager Certification (APICS CSCP)','Moving'),
('Moving Company DOT License','Moving'),
('Packing and Crating Technician Certification','Moving'),
('Piano Moving Specialist Certification','Moving'),
('Records Management Specialist Certification','Moving'),
('Rigging and Machinery Moving Certification','Moving'),
('Self Storage Manager Certification (SSA)','Moving'),
('Aquatic Herbicide Applicator License','Pest Control'),
('Bed Bug Inspection Technician Certification','Pest Control'),
('Biocide Technician Certification','Pest Control'),
('Bird Control Specialist Certification','Pest Control'),
('Certified Pool Operator License (CPO)','Pest Control'),
('Commercial Pesticide Applicator License','Pest Control'),
('Fumigation Contractor License','Pest Control'),
('Indoor Air Quality Investigator Certification','Pest Control'),
('Industrial Hygienist Associate (AIH)','Pest Control'),
('Mold Inspector Certification (MICRO)','Pest Control'),
('Mosquito Abatement Specialist Certification','Pest Control'),
('Pest Control Supervisor License','Pest Control'),
('Pool and Spa Chemical Technician License','Pest Control'),
('Radon Inspector Certification','Pest Control'),
('Rodent Control Specialist Certification','Pest Control'),
('Urban Wildlife Management Certification','Pest Control'),
('Vegetation Management License','Pest Control'),
('Water Quality Analyst Certification','Pest Control'),
('Weed Control Applicator License','Pest Control'),
('Wood Destroying Insect Inspector Certification','Pest Control'),
('Animal Control Officer Certification','Pet Care'),
('Aquaculture Specialist Certification','Pet Care'),
('Avian Care Specialist Certification','Pet Care'),
('Cat Behavior Specialist Certification','Pet Care'),
('Certified Master Groomer (CMG)','Pet Care'),
('Certified Professional Dog Trainer (CPDT-KA)','Pet Care'),
('Certified Professional Dog Trainer Advanced (CPDT-KSA)','Pet Care'),
('Certified Service Dog Trainer','Pet Care'),
('Dog Behavior Consultant Certification (CDBC)','Pet Care'),
('Exotic Animal Keeper Certification','Pet Care'),
('Fear Free Certified Professional','Pet Care'),
('International Association of Animal Behavior Consultants Certification','Pet Care'),
('Kennel Manager Certification','Pet Care'),
('National Certified Master Groomer (NCMG)','Pet Care'),
('Pet First Aid and CPR Certification','Pet Care'),
('Pet Nutritionist Certification','Pet Care'),
('Pet Sitter Certification (PSI)','Pet Care'),
('Registered Veterinary Technician License (RVT)','Pet Care'),
('Therapy Dog Evaluator Certification','Pet Care'),
('Veterinary Receptionist Certification','Pet Care'),
('Veterinary Technician License (CVT)','Pet Care'),
('360 VR Videographer Certification','Photography'),
('Adobe Certified Professional Photoshop','Photography'),
('After Effects Certified Animator','Photography'),
('Certified Professional Photographer (CPP)','Photography'),
('Certified Social Media Strategist (SMMU)','Photography'),
('Certified Video Editor (Adobe Premiere)','Photography'),
('Content Creator Certification (HubSpot)','Photography'),
('DaVinci Resolve Certified Colorist','Photography'),
('FAA Part 107 Remote Pilot Certificate','Photography'),
('Final Cut Pro Certified Editor','Photography'),
('Green Screen Technician Certification','Photography'),
('Live Stream Technician Certification','Photography'),
('Master Photographer Certification (PPA)','Photography'),
('Photographic Craftsman Certification (PPA)','Photography'),
('Photography Studio Manager Certification','Photography'),
('Podcast Producer Certification','Photography'),
('Sports Photographer Certification (NPPA)','Photography'),
('USCG Drone Over Water Waiver','Photography'),
('Wedding Videographer Certification (WEVA)','Photography'),
('YouTube Certified Creator','Photography'),
('ASSE 1060 Residential Deck Drain Inspector','Plumbing'),
('CIPP Liner Installer Certification','Plumbing'),
('Certified Plumbing Inspector (CPI)','Plumbing'),
('Cross-Connection Control Specialist Certification','Plumbing'),
('Drain Layer License','Plumbing'),
('Fire Suppression Systems Certification (NICET Level II)','Plumbing'),
('Gas Fitter License','Plumbing'),
('Grease Trap Service Technician Certification','Plumbing'),
('Greywater System Installer License','Plumbing'),
('Hydro Jetting Technician Certification','Plumbing'),
('Hydronics Heating Technician Certification','Plumbing'),
('IAPMO Plumbing Inspector Certification','Plumbing'),
('Liquefied Petroleum Gas (LPG) Contractor License','Plumbing'),
('National Standard Plumber Certification','Plumbing'),
('Oil Burner Technician License','Plumbing'),
('Pipefitter Journeyman License','Plumbing'),
('Pipefitter License','Plumbing'),
('Plumbing Contractor Qualifier License','Plumbing'),
('Plumbing Design Engineer License','Plumbing'),
('Plumbing Foreman License','Plumbing'),
('Plumbing Project Manager Certification','Plumbing'),
('Pool and Spa Plumbing License','Plumbing'),
('Radiant Floor Heating Installer Certification','Plumbing'),
('Rainwater Harvesting System Installer Certification','Plumbing'),
('Refrigeration Pipefitter License','Plumbing'),
('Sewer Inspection Technician NASSCO Certification','Plumbing'),
('Solar Water Heating Installer Certification','Plumbing'),
('Steamfitter License','Plumbing'),
('Tankless Water Heater Installer Certification','Plumbing'),
('Underground Utility Contractor License','Plumbing'),
('Water Well Contractor License','Plumbing'),
('Water Well Pump Installer License','Plumbing'),
('Accredited Buyer Representative (ABR)','Real Estate'),
('Accredited Land Consultant (ALC)','Real Estate'),
('Appraisal Institute MAI Designation','Real Estate'),
('At Home with Diversity Certification (AHWD)','Real Estate'),
('Building Operator Certification (BOC)','Real Estate'),
('Certified Commercial Investment Member (CCIM)','Real Estate'),
('Certified International Property Specialist (CIPS)','Real Estate'),
('Certified Property Maintenance Manager (CPMM)','Real Estate'),
('Commercial Property Manager Certification','Real Estate'),
('Commercial Real Estate License','Real Estate'),
('Distressed Property Expert Certification (CDPE)','Real Estate'),
('Facility Manager Certification (CFM)','Real Estate'),
('General Certified Appraiser License','Real Estate'),
('LEED AP Operations + Maintenance','Real Estate'),
('Military Relocation Professional (MRP)','Real Estate'),
('Property and Evidence Technician Certification','Real Estate'),
('Real Estate Auction License','Real Estate'),
('Residential Rental Property Manager Certification','Real Estate'),
('Senior Real Estate Specialist (SRES)','Real Estate'),
('Short Sales and Foreclosure Resource (SFR)','Real Estate'),
('Society of Industrial and Office Realtors (SIOR)','Real Estate'),
('CertainTeed ShingleMaster Certification','Roofing'),
('Chimney Inspector Certification (CSIA Level 2)','Roofing'),
('Chimney Sweep Certification (CSIA)','Roofing'),
('Commercial Roofing License','Roofing'),
('Exterior Insulation Finish System (EIFS) Contractor License','Roofing'),
('GAF Master Elite Roofing Certification','Roofing'),
('Gutter Installer Certification','Roofing'),
('ICC Residential Roofing Inspector Certification','Roofing'),
('Low-Slope Roofing Contractor License','Roofing'),
('Metal Roofing Contractor Certification (MBCI)','Roofing'),
('NRCA ProCertification Low Slope','Roofing'),
('NRCA ProCertification Steep Slope','Roofing'),
('Polyurea Coating Applicator Certification','Roofing'),
('Roofing Journeyman License','Roofing'),
('Siding Contractor License','Roofing'),
('Solar Panel Roof Installer Certification','Roofing'),
('Steep-Slope Roofing Contractor License','Roofing'),
('Storm Damage Restoration Contractor Certification','Roofing'),
('Tile Roofing Installer Certification (TRI)','Roofing'),
('Underlayment Installer Certification','Roofing'),
('Window Installation Contractor License','Roofing'),
('AWS Certified Developer Associate','Tech Support'),
('AWS Certified Security Specialty','Tech Support'),
('AWS Certified SysOps Administrator','Tech Support'),
('Apple Certified iOS Technician (ACiT)','Tech Support'),
('Certified Ethical Hacker Advanced (CPENT)','Tech Support'),
('Certified Information Privacy Professional (CIPP)','Tech Support'),
('Certified Information Systems Auditor (CISA)','Tech Support'),
('Cisco CCNP Certification','Tech Support'),
('Cisco CCSP Certification','Tech Support'),
('CompTIA CASP+ Certification','Tech Support'),
('CompTIA Cloud+ Certification','Tech Support'),
('CompTIA CySA+ Certification','Tech Support'),
('CompTIA Data+ Certification','Tech Support'),
('CompTIA Linux+ Certification','Tech Support'),
('CompTIA PenTest+ Certification','Tech Support'),
('CompTIA Server+ Certification','Tech Support'),
('Cybersecurity Analyst Certification (CySA+)','Tech Support'),
('Drone Repair Technician Certification','Tech Support'),
('Google Cloud Professional Data Engineer','Tech Support'),
('Google Workspace Administrator Certification','Tech Support'),
('HDI Desktop Support Technician Certification','Tech Support'),
('Low Voltage Technician Certification (BICSI)','Tech Support'),
('Microsoft Certified: Azure Developer Associate','Tech Support'),
('Microsoft Certified: Azure Security Engineer','Tech Support'),
('Microsoft Certified: Power BI Data Analyst','Tech Support'),
('Smart Home Installer Certification (CEDIA)','Tech Support'),
('VMware Certified Professional (VCP)','Tech Support')
ON CONFLICT (name) DO NOTHING;
